Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
0
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
24
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 2, in <module>
    for i in range[1,5]:
TypeError: 'type' object is not subscriptable
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
120
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 1, in <module>
    from arrey import *
ModuleNotFoundError: No module named 'arrey'
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
(1, 2, 3, 4, 5)
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
(1, 2, 3, 4, 5)
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
1
2
3
4
5
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
10
115
123
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
10
115
123
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
(10, 115, 123, 190, 203, 343)
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
(10, 115, 123, 190, 203, 343)
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 4, in <module>
    arr2=add(arr,arr1)
NameError: name 'add' is not defined
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 4, in <module>
    arr2=add(arr,arr1)
NameError: name 'add' is not defined
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 4, in <module>
    arr2=add(arr,arr1)
NameError: name 'add' is not defined
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 4, in <module>
    print(add(arr,arr1))
NameError: name 'add' is not defined
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 4, in <module>
    print(add(arr,arr1))
NameError: name 'add' is not defined
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 2, in <module>
    from numpy import *
ModuleNotFoundError: No module named 'numpy'
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 2, in <module>
    from numpy import *
ModuleNotFoundError: No module named 'numpy'
>>> 
=================== RESTART: C:/Users/anil/Desktop/fact.py ===================
Traceback (most recent call last):
  File "C:/Users/anil/Desktop/fact.py", line 5, in <module>
    arr2[i]=arr[i]+arr[i]
NameError: name 'arr2' is not defined
>>> 
